notifications:
  email: false
git:
  quiet: true
  depth: false
jdk: openjdk11
node_js: lts/*
services:
  - docker
  - xvfb
python: 3.7
matrix:
  include:
    - python: 3.7
addons:
  apt:
    update: false
    packages:
      - jq
      - bash
      - curl
      - tree
      - docker-ce
      - libxml2-utils
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
      - python3-setuptools
      - python3-pip
install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  #
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip -V
  - docker-compose version
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie docker-compose
  - http --version --debug
  - pip -V
jobs:
  include:
    - stage: test
      jdk: openjdk11
      name: test step0
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step0-zero-configuration clean package docker:build docker:start
        - wait_for 8080
        - http :8080
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step0-zero-configuration docker:stop docker:remove
        - stop_any 8080
    - stage: test
      jdk: openjdk11
      name: test step1
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step1-zero-configuration clean package docker:build docker:start
        - wait_for 8080
        - http :8080
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step1-zero-configuration docker:stop docker:remove
        - stop_any 8080
    - stage: test
      jdk: openjdk11
      name: test step2
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step2-zero-configuration
        - wait_for 8080
        - http :8080
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f step2-zero-configuration docker:stop docker:remove
        - stop_any 8080
    - stage: test
      jdk: openjdk11
      name: versions display-property-updates
      script: ./mvnw versions:display-property-updates
cache:
  npm: true
  pip: true
  packages: true
  directories:
    - ~/.m2
    - ~/.docker
    - ~/.local/daggerok
